#!/usr/bin/env node
// Generate color code tokens (JSON / Kotlin Compose / CSS) from brand.config.json,
// so the icon system, wordmark, and app UI all share one source of truth.
// Usage: node scripts/generate-tokens.mjs --config brand.config.json --out out/tokens
import { mkdirSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

// Fixed brand palette constants (the brand's identity colors, not per-product accents).
const BRAND = {
  vitalGreen: '#00E091',
  leaf:       '#22C55E',
  emerald:    '#059669',
  forestInk:  '#0F2922', // text / dark background
  mist:       '#F2FBF7',
};

// #RRGGBB -> 0xFFRRGGBB (Compose ARGB literal, opaque alpha).
function hexToArgb(hex) {
  const h = hex.replace('#', '').toUpperCase();
  return `0xFF${h}`;
}
// camelCase -> kebab-case (vitalGreen -> vital-green).
function kebab(s) {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}
// vitalGreen -> VitalGreen (Kotlin val name).
function pascal(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const args = Object.fromEntries(
  process.argv.slice(2).reduce((a, v, i, arr) => (v.startsWith('--') ? [...a, [v.slice(2), arr[i + 1]]] : a), [])
);
const here = dirname(fileURLToPath(import.meta.url));
const cfg = JSON.parse(readFileSync(args.config || join(here, '..', 'brand.config.json'), 'utf8'));
const OUT = args.out || join(here, '..', 'out', 'tokens');

function w(rel, c) { const p = join(OUT, rel); mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, c); }

// --- build the machine-readable model ---
const products = {};
for (const p of cfg.products) {
  products[p.key] = {
    name: p.name,
    accent: p.bg,
    accentDark: p.bgDark || p.bg,
    symbol: p.fg,
  };
}
const themes = {};
for (const t of cfg.themes) {
  const entry = { label: t.label };
  if (t.bg) entry.bg = t.bg;
  if (t.fg) entry.fg = t.fg;
  if (t.accent) entry.accent = t.accent;
  themes[t.key] = entry;
}

const tokens = { brand: { ...BRAND }, products, themes };

// 1) tokens.json
w('tokens.json', JSON.stringify(tokens, null, 2) + '\n');

// 2) Color.kt — Compose tokens
const brandVals = Object.entries(BRAND)
  .map(([k, hex]) => `    val ${pascal(k)} = Color(${hexToArgb(hex)})`)
  .join('\n');

const productEntries = Object.entries(products)
  .map(([k, p]) =>
    `        "${k}" to ProductColors(\n` +
    `            accent = Color(${hexToArgb(p.accent)}),\n` +
    `            accentDark = Color(${hexToArgb(p.accentDark)}),\n` +
    `            symbol = Color(${hexToArgb(p.symbol)}),\n` +
    `        ),`)
  .join('\n');

const colorKt = `// Generated by scripts/generate-tokens.mjs from brand.config.json — do not edit by hand.
package cl.butake.buky.theme

import androidx.compose.ui.graphics.Color

/** Per-product color set: [accent] is the distinctive bg, [symbol] the foreground glyph color. */
data class ProductColors(
    val accent: Color,
    val accentDark: Color,
    val symbol: Color,
)

/** Single source of truth for Buky brand colors, derived from brand.config.json. */
object BukyColors {
    // Brand palette
${brandVals}

    // Per-product accents, keyed by product key.
    val products: Map<String, ProductColors> = mapOf(
${productEntries}
    )

    /** Convenience lookup; falls back to the flagship forest/mint pairing. */
    fun product(key: String): ProductColors =
        products[key] ?: ProductColors(ForestInk, ForestInk, VitalGreen)
}
`;
w('Color.kt', colorKt);

// 3) tokens.css
const brandCss = Object.entries(BRAND)
  .map(([k, hex]) => `  --buky-${kebab(k)}: ${hex};`)
  .join('\n');

const productCss = Object.entries(products)
  .map(([k, p]) =>
    `  --buky-${k}-accent: ${p.accent};\n` +
    `  --buky-${k}-accent-dark: ${p.accentDark};\n` +
    `  --buky-${k}-symbol: ${p.symbol};`)
  .join('\n');

const tokensCss = `/* Generated by scripts/generate-tokens.mjs from brand.config.json — do not edit by hand. */
:root {
  /* Brand palette */
${brandCss}

  /* Per-product accents */
${productCss}
}
`;
w('tokens.css', tokensCss);

console.log(`brandkit: generated color tokens (tokens.json, Color.kt, tokens.css) -> ${OUT}`);
